name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to finalize (e.g. 1.2.3)'
        required: true

jobs:
  finalize-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Convert Pre-Release to Final
        run: |
          VERSION="${{ github.event.inputs.version }}"
          API_URL="https://api.github.com/repos/${{ github.repository }}/releases"
          RELEASE_ID=$(curl -s \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            $API_URL \
            | jq -r '[.[] | select(.tag_name | test("^v" + env.VERSION + "-rc\\.\\d+$"))] | sort_by(.tag_name) | last | .id')

          if [ "$RELEASE_ID" = "null" ] || [ -z "$RELEASE_ID" ]; then
            echo "No pre-release found for version $VERSION"
            exit 1
          fi

          curl -s \
            -X PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            $API_URL/$RELEASE_ID \
            -d '{"tag_name":"v'"$VERSION"'","prerelease":false,"name":"Release v'"$VERSION"'","make_latest":true}'
